### ISSUE TITLE
Katselmointipyyntö

### ISSUE THREAD

**Issue by romeorusi** [Ohjelmistoprojekti2-Black/mtt-backend#5]
https://github.com/Ohjelmistoprojekti2-Black/mtt-backend/blob/main/src/main/java/com/op2/op2/domain/Event.java#L21-L36 
Katselmoidaan validointi
https://github.com/Ohjelmistoprojekti2-Black/mtt-backend/blob/main/src/main/java/com/op2/op2/web/EventController.java#L57-L67
Katselmoi saveEvent metodi
https://github.com/Ohjelmistoprojekti2-Black/mtt-backend/blob/main/src/main/resources/templates/addevent.html#L19-L34
html tiedoston Name ja Date
https://github.com/Ohjelmistoprojekti2-Black/mtt-backend/blob/main/src/test/java/com/op2/op2/RepositoryTests.java#L23-L67 
Testauksesta katsellaan jokainen testaus

Validoinnit lisätty, jotta käyttäjän syötteet vastaavat tietohakemiston määrittelemiä arvoja ja rajoituksia. Testaaminen on hoidettu yksikkötesteillä RepositoryTests.java luokassa, sekä testaamalla eri toiminnallisuuksia manuaalisesti.

**Comment by ValtteriRaatikainen** [comment]
Validointi näyttää selkeältä, mutta kommentointi voisi helpottaa toiminnallisuuksien ymmärtämistä.

saveEvent metodi on kirjoitettu selkeästi ja simppelisti. Plussapisteitä erroreiden tarkistuksesta ennen tallennusta. Metodi on myös nimetty asianmukaisesti.

Jälleen kerran hienosti koodattua thymeleaffia, koodi on selkeästi luettavaa, koska se on hyvin jäsenneltyä. 

Hyvin testattu monipuolisesti erilaisia tilanteita, mutta deleteEventTest-metodissa on kommentoitua koodia jota ei tarvita. Tämän voisi poistaa. 

Yhteenvetona sanoisimme että tiiminne on tehnyt loistavaa työtä. Koodi on helppolukuista, selkeästi rivitetty ja pidetty mielessä kaikenlaiset eri tilanteet testien muodossa. Kommentointia voisi kuitenkin hieman lisätä. Mahtavaa työtä, jatkakaa samaan malliin! 👍
