### ISSUE TITLE
Katselmointipyyntö #2 team-white 

### ISSUE THREAD

**Issue by romeorusi** [Ohjelmistoprojekti2-Black/mtt-backend#8]
https://github.com/Ohjelmistoprojekti2-Black/mtt/blob/main/frontend/src/components/Weather.jsx#L10-L31

Katselmoikaa sään noutamisen logiikka ja koodin hyvien käytäntöjen mukaisuutta.

https://github.com/Ohjelmistoprojekti2-Black/mtt-backend/blob/main/frontend/src/components/MyEvents.jsx#L58-L90

Onko eventtien listaus hyvien käytäntöjen mukaisesti tehty?

https://github.com/Ohjelmistoprojekti2-Black/mtt/blob/main/frontend/src/components/FrontPage.jsx#L55-L132
Kaupunkien tapahtumien API-datan fetch. Onko hyvän käytäntöjen mukainen, voiko koodia tiivistää?

https://github.com/Ohjelmistoprojekti2-Black/mtt/blob/main/frontend/src/components/UserLocation.jsx#L6-L48
Käyttäjän sijainnin haku. Voiko tämän tehdä helpommalla tai kätevämmällä tavalla?

**Comment by attemkinen** [comment]
https://github.com/Ohjelmistoprojekti2-Black/mtt/blob/main/frontend/src/components/Weather.jsx#L10-L31
muuttujat fiksusti nimettyä ja niiden tarkoitus on helposti ymmärrettävissä tämän takia. Kommentointi kumminkin puuttuu kokonaan. Hyvänä lisänä tässä kumminkin api avaimen käyttö!

https://github.com/Ohjelmistoprojekti2-Black/mtt-backend/blob/main/frontend/src/components/MyEvents.jsx#L58-L90
erittäin hyvin tehty listaus! mutta kommentointi helpottaisi koodin luettavuutta ja ymmärrettävyyttä.

https://github.com/Ohjelmistoprojekti2-Black/mtt/blob/main/frontend/src/components/FrontPage.jsx#L55-L132
Koodia voisi tiivistää  vaikka yhdistämällä toistuvia osia esimerkiksi aikojen muotoilu voisi olla yhdessä funktiossa jotai voi kutsua eri paikoissa. Ja esim hintojen puuttumis tilanteessa voisi käyttää oletusarvoja monien ehtolauseiden sijasta

https://github.com/Ohjelmistoprojekti2-Black/mtt/blob/main/frontend/src/components/UserLocation.jsx#L6-L48
Hyvin kirjoitettua koodia. Ainoana huomiona voisi olla käyttäjän suostumus. Voisiko tähän lisätä että käyttäjältä kysytään lupaa sijaintitietojen jakoon.
